pipeline:
    name: prenv
    identifier: prenv
    projectIdentifier: simple_gs_1
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              template:
                  templateRef: harness_app
                  versionLabel: v1
                  templateInputs:
                      type: Approval
                      spec:
                          execution:
                              steps:
                                  - step:
                                        identifier: a1
                                        type: HarnessApproval
                                        spec:
                                            approvers:
                                                userGroups: <+input>
        - stage:
              name: yg
              identifier: yg
              template:
                  templateRef: harness_app
                  versionLabel: v1
                  templateInputs:
                      type: Approval
                      spec:
                          execution:
                              steps:
                                  - step:
                                        identifier: a1
                                        type: HarnessApproval
                                        spec:
                                            approvers:
                                                userGroups: <+input>
    allowStageExecutions: true
