pipeline:
    name: remote one
    identifier: remote1
    description: here to stay for real
    projectIdentifier: simple_gs_1
    orgIdentifier: default
    tags: {}
    allowStageExecutions: true
    stages:
        - stage:
              name: a
              identifier: a
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: a1
                                identifier: a1
                                type: HarnessApproval
                                timeout: 10m
                                spec:
                                    approvalMessage: <+input>
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.default_peeps
                                            - account.rbac_peeps
                                            - account.adminsOnly
                                    approverInputs: []
              tags: {}
        - stage:
              name: b
              identifier: b
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: a1
                                identifier: a1
                                type: HarnessApproval
                                timeout: 10m
                                spec:
                                    approvalMessage: <+input>
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.default_peeps
                                            - account.rbac_peeps
                                            - account.adminsOnly
                                    approverInputs: []
              tags: {}
        - stage:
              name: c
              identifier: c
              template:
                  templateRef: simple_harness_approval_
                  versionLabel: v1
                  templateInputs:
                      type: Approval
                      spec:
                          execution:
                              steps:
                                  - step:
                                        identifier: a1
                                        type: HarnessApproval
                                        spec:
                                            approvalMessage: jhbjugvyfctdghv
