pipeline:
    name: input set curr error exp
    identifier: input_set_curr_error_exp
    projectIdentifier: naidu_simplified_git_exp
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: "e1"
              identifier: "e1"
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: "e1"
                                identifier: "e1"
                                type: HarnessApproval
                                timeout: <+input>
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups: <+input>
                                    approverInputs: []
              tags: {}
