pipeline:
    name: only non def
    identifier: only_non_def
    projectIdentifier: naidu_simplified_git_exp
    orgIdentifier: default
    description: pipeline desc
    tags: {}
    variables:
        - name: var2
          type: String
          value: <+input>
    stages:
        - stage:
              name: a1
              identifier: a1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: "e1"
                                identifier: "e1"
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.Read
                                    approverInputs: []
              tags: {}
