pipeline:
    name: pipeline service
    identifier: pipeline_service
    projectIdentifier: naidu_simplified_git_exp
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: oiuhyg
              identifier: oiuhyg
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: ionu
                                identifier: ionu
                                type: HarnessApproval
                                timeout: <+input>
                                spec:
                                    approvalMessage: <+input>
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.Read
                                    approverInputs: []
              tags: {}
