pipeline:
  name: remremrem
  identifier: remremrem
  projectIdentifier: testing
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: rem
        identifier: rem
        description: ""
        type: Customs
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
