pipeline:
    name: pipeline
    identifier: pipeline
    projectIdentifier: git_sync_test_proj
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: stage1
              identifier: stage1
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: sevrvice1
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: envw
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.testK8sConnectorNgGN
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: true
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: shell
                                identifier: shell
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo hi
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
