pipeline:
  name: demo pipeline
  identifier: demo_pipeline
  description: null
  stages:
  - stage:
      name: be
      identifier: be
      description:
      type: Deployment
      spec:
        serviceConfig:
          serviceDefinition:
            type: Kubernetes
            spec:
              manifestOverrideSets: []
              manifests:
              - manifest:
                  identifier: m1
                  spec:
                    store:
                      type: Github
                      spec:
                        connectorRef: namanvermah
                        gitFetchType: Branch
                        paths:
                        - pipelines/.harness
                        repoName: git-sync-be
                        branch: master
                    skipResourceVersioning: false
                  type: K8sManifest
              artifacts:
                sidecars: []
          service:
            name: be-service
            identifier: beservice
        infrastructure:
          environment:
            name: be-env
            identifier: beenv
            type: PreProduction
          infrastructureDefinition:
            type: KubernetesDirect
            spec:
              connectorRef: invalid_connector
              namespace: <+input>
              releaseName: <+input>
          allowSimultaneousDeployments: false
          infrastructureKey:
        execution:
          steps:
          - step:
              type: ShellScript
              name: echo
              identifier: echo
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: echo <+pipeline.stages.be.spec.infrastructure.infrastructureDefinition.spec.namespace>
                environmentVariables: []
                outputVariables: []
                executionTarget: {}
              timeout: 10m
          rollbackSteps: []
      tags: {}
      failureStrategies:
      - onFailure:
          errors:
          - AnyOther
          action:
            type: StageRollback
    parallel: null
  - stage:
      name: ui
      identifier: ui
      description:
      type: Deployment
      spec:
        serviceConfig:
          serviceDefinition:
            type: Kubernetes
            spec:
              manifestOverrideSets: []
              manifests:
              - manifest:
                  identifier: m1
                  spec:
                    store:
                      type: Github
                      spec:
                        connectorRef: namanvermah
                        gitFetchType: Branch
                        paths:
                        - /.harness/
                        repoName: git-sync
                        branch: <+input>
                    skipResourceVersioning: false
                  type: K8sManifest
              artifacts:
                sidecars: []
          service:
            name: ui-service
            identifier: uiservice
        infrastructure:
          environment:
            name: ui-env
            identifier: uienv
            type: PreProduction
          infrastructureDefinition:
            type: KubernetesDirect
            spec:
              connectorRef: invalid_connector
              namespace: <+input>
              releaseName: <+input>
          allowSimultaneousDeployments: false
          infrastructureKey:
        execution:
          steps:
          - step:
              type: ShellScript
              name: echo
              identifier: echo
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: echo <+pipeline.stages.ui.spec.infrastructure.infrastructureDefinition.spec.namespace>
                environmentVariables: []
                outputVariables: []
                executionTarget: {}
              timeout: 10m
          rollbackSteps: []
      tags: {}
      failureStrategies:
      - onFailure:
          errors:
          - AnyOther
          action:
            type: StageRollback
    parallel: null
  orgIdentifier: default
  projectIdentifier: Git_Sync_Project
