pipeline:
  name: p5
  identifier: p5
  description:
    expression: false
    value: test description
    typeString: true
    jsonResponseField: false
  stages:
  - stage:
      name: s1
      identifier: s1
      description:
      type: Deployment
      spec:
        serviceConfig:
          serviceDefinition:
            type: Kubernetes
            spec:
              manifestOverrideSets: []
              manifests: []
              artifacts:
                sidecars: []
          service:
            name: s5
            identifier: s5
        infrastructure:
          infrastructureDefinition:
            type: KubernetesDirect
            spec:
              connectorRef: <+input>
              namespace: aa
              releaseName: dd
          allowSimultaneousDeployments: false
          infrastructureKey: ff
          environment:
            name: e5
            identifier: e5
            type: PreProduction
        execution:
          steps:
          - step:
              name: Rollout Deployment
              identifier: rolloutDeployment
              type: K8sRollingDeploy
              timeout: 10m
              spec:
                skipDryRun: false
          rollbackSteps:
          - step:
              name: Rollback Rollout Deployment
              identifier: rollbackRolloutDeployment
              type: K8sRollingRollback
              timeout: 10m
              spec: {}
      tags: {}
      failureStrategies:
      - onFailure:
          errors:
          - AnyOther
          action:
            type: StageRollback
    parallel: null
  orgIdentifier: default
  projectIdentifier: Git_Sync_Project
