pipeline:
  name: p7
  identifier: p7
  description: testing overlay update
  stages:
  - stage:
      name: s1
      identifier: s1
      description: this
      type: Deployment
      spec:
        serviceConfig:
          serviceDefinition:
            type: Kubernetes
            spec:
              manifestOverrideSets: []
              manifests: []
              artifacts:
                sidecars: []
                primary:
                  type: DockerRegistry
                  spec:
                    connectorRef: harnessImage
                    imagePath: library/nginx
                    tag: <+input>
          service:
            name: s135
            identifier: s135
        infrastructure:
          environment:
            name: e234
            identifier: e234
            type: PreProduction
          infrastructureDefinition:
            type: KubernetesDirect
            spec:
              connectorRef: account.temp
              namespace: <+input>
              releaseName: release
          allowSimultaneousDeployments: false
          infrastructureKey: e
        execution:
          steps:
          - step:
              name: Rollout Deployment
              identifier: rolloutDeployment
              type: K8sRollingDeploy
              timeout: 10m
              spec:
                skipDryRun: false
          rollbackSteps:
          - step:
              name: Rollback Rollout Deployment
              identifier: rollbackRolloutDeployment
              type: K8sRollingRollback
              timeout: 10m
              spec: {}
      tags: {}
      failureStrategies:
      - onFailure:
          errors:
          - AnyOther
          action:
            type: StageRollback
      serviceType:
        text: Service
        value: service
        icon: service
        disabled: false
    parallel: null
  orgIdentifier: default
  projectIdentifier: Git_Sync_Project
