pipeline:
    name: something
    identifier: something
    projectIdentifier: Git_Sync_Project
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: something
              identifier: something
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              manifestOverrideSets: []
                              manifests: []
                              artifacts:
                                  sidecars: []
                      service:
                          name: something
                          identifier: something
                  infrastructure:
                      environment:
                          name: something
                          identifier: something
                          type: PreProduction
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: <+pipeline.name>
                              namespace: aa
                              releaseName: ss
                      allowSimultaneousDeployments: false
                      infrastructureKey: ""
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                          - step:
                                type: K8sApply
                                name: ssss
                                identifier: ssss
                                spec:
                                    skipDryRun: false
                                    skipSteadyStateCheck: false
                                    filePaths:
                                        - test
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
