pipeline:
  name: something
  identifier: something
  description: null
  stages:
  - stage:
      name: something
      identifier: something
      description:
      type: Deployment
      spec:
        serviceConfig:
          serviceDefinition:
            type: Kubernetes
            spec:
              manifestOverrideSets: []
              manifests: []
              artifacts:
                sidecars: []
          service:
            name: something
            identifier: something
        infrastructure:
          environment:
            name: something
            identifier: something
            type: PreProduction
        execution:
          steps:
          - step:
              name: Rollout Deployment
              identifier: rolloutDeployment
              type: K8sRollingDeploy
              timeout: 10m
              spec:
                skipDryRun: false
          rollbackSteps:
          - step:
              name: Rollback Rollout Deployment
              identifier: rollbackRolloutDeployment
              type: K8sRollingRollback
              timeout: 10m
              spec: {}
      tags: {}
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
    parallel: null
  orgIdentifier: default
  projectIdentifier: Git_Sync_Project
