pipeline:
  name: test github connector
  identifier: test_github_connector
  description: null
  stages:
  - stage:
      name: shell script stage
      identifier: shell_script_stage
      description:
      type: Deployment
      spec:
        serviceConfig:
          serviceDefinition:
            type: Kubernetes
            spec:
              manifestOverrideSets: []
              manifests:
              - manifest:
                  identifier: m1
                  spec:
                    store:
                      type: Github
                      spec:
                        connectorRef: namanvermah
                        gitFetchType: Branch
                        paths:
                        - pipelines/.harness/emptyYaml.yaml
                        repoName: git-sync
                        branch: master
                    skipResourceVersioning: false
                  type: K8sManifest
              artifacts:
                sidecars: []
          service:
            name: service931
            identifier: service931
        infrastructure:
          environment:
            name: env201
            identifier: env201
            type: PreProduction
          infrastructureDefinition:
            type: KubernetesDirect
            spec:
              connectorRef: invalid_connector
              namespace: <+input>
              releaseName: <+input>
          allowSimultaneousDeployments: false
          infrastructureKey:
        execution:
          steps:
          - step:
              type: ShellScript
              name: echo
              identifier: echo
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: <+input>
                environmentVariables: []
                outputVariables: []
                executionTarget: {}
              timeout: 10m
          rollbackSteps: []
      tags: {}
      failureStrategies:
      - onFailure:
          errors:
          - AnyOther
          action:
            type: StageRollback
    parallel: null
  orgIdentifier: default
  projectIdentifier: Git_Sync_Project
