pipeline:
    stages:
        - stage:
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: Http
                                timeout: 10m
                                spec:
                                    url: <+input>
                                    method: GET
                                    outputVariables: [
                                name: search
                                identifier: search
              name: a1
              identifier: a1
    projectIdentifier: Git_Sync_Manager
    orgIdentifier: default
    name: approval 1
    identifier: approval_1
