pipeline:
    name: m bac
    identifier: m_bac
    projectIdentifier: Git_Sync_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: e
                                identifier: e
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: <+input>
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                  serviceDependencies: []
              tags: {}
