pipeline:
    name: preflight invalid conn
    identifier: preflight_invalid_conn
    projectIdentifier: Git_Sync_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: d1
              identifier: d1
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: s1
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              artifacts:
                                  primary:
                                      type: DockerRegistry
                                      spec:
                                          connectorRef: nvh_docker
                                          imagePath: library/nginx
                                          tag: latest
                  infrastructure:
                      environmentRef: "e1"
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.does_not_work
                              namespace: sssas
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: echo
                                identifier: echo
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo done
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
