pipeline:
    name: approval remote
    identifier: approval_remote
    projectIdentifier: simple_gs_2
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: admins
                                identifier: admins
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.adminsOnly
                                    approverInputs: []
              tags: {}
