pipeline:
    name: many branches
    identifier: many_branches
    projectIdentifier: simple_gs_2
    orgIdentifier: default
    storeType: REMOTE
    remoteType: create
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              template:
                  templateRef: approval_shell
                  versionLabel: v1
