pipeline:
    name: many branches
    identifier: many_branches
    projectIdentifier: simple_gs_2
    orgIdentifier: default
    storeType: REMOTE
    remoteType: create
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              template:
                  templateRef: approval_shell
                  versionLabel: v1
        - stage:
              name: mhvgcf
              identifier: mhvgcf
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: ilhkujyhg
                                identifier: ilhkujyhg
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.adminsOnly
                                    approverInputs: []
              tags: {}
