pipeline:
    stages:
        - stage:
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: Http
                                timeout: 15s
                                spec:
                                    url: <+input>
                                    method: GET
                                name: search
                                identifier: search
              name: a1
              identifier: a1
    projectIdentifier: nvh_git_sync
    orgIdentifier: default
    name: create pipeline test
    identifier: create_pipeline_test
