pipeline:
    name: execution details
    identifier: execution_details
    projectIdentifier: nvh_git_sync
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: Http
                                name: search
                                identifier: search
                                spec:
                                    url: https://www.google.com
                                    method: GET
                                    headers: []
                                    outputVariables: []
                                timeout: 1m
                  serviceDependencies: []
              tags: {}
