pipeline:
    stages:
        - stage:
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: Http
                                timeout: 15m
                                spec:
                                    url: https://www.google.com
                                    method: GET
                                name: search
                                identifier: search
              name: a1
              identifier: a1
    projectIdentifier: nvh_git_sync
    orgIdentifier: default
    name: update to new branch
    identifier: update_to_new_branch
