pipeline:
    name: update to new branch
    identifier: update_to_new_branch
    projectIdentifier: nvh_git_sync
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: Http
                                name: search
                                identifier: search
                                spec:
                                    url: https://www.google.com
                                    method: GET
                                    headers: []
                                    outputVariables: []
                                timeout: 10s
                          - step:
                                type: Http
                                name: search again
                                identifier: search_again
                                spec:
                                    url: https://www.yahoo.com
                                    method: GET
                                    headers: []
                                    outputVariables: []
                                timeout: 10s
                  serviceDependencies: []
              tags: {}
