pipeline:
    name: a
    identifier: a
    allowStageExecutions: true
    projectIdentifier: GS_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              template:
                  templateRef: ApprovalShell
                  versionLabel: Version1
        - stage:
              name: a2
              identifier: a2
              template:
                  templateRef: ApprovalShell
                  versionLabel: Version1
