pipeline:
    name: a1
    identifier: a1
    allowStageExecutions: true
    projectIdentifier: GS_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              template:
                  templateRef: ApprovalShell
                  versionLabel: Version1
        - stage:
              name: a3
              identifier: a3
              template:
                  templateRef: ApprovalShell
                  versionLabel: Version1
