pipeline:
    name: a2
    identifier: a2
    allowStageExecutions: false
    projectIdentifier: GS_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              template:
                  templateRef: ApprovalShell
                  versionLabel: Version1
