pipeline:
    name: asd
    identifier: asd
    projectIdentifier: GS_Manager
    orgIdentifier: default
    storeType: ""
    remoteType: create
    tags: {}
    stages:
        - stage:
              name: asd
              identifier: asd
              template:
                  templateRef: deploy_shell
                  versionLabel: version1
