pipeline:
    name: d
    identifier: d
    projectIdentifier: GS_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: ds
              identifier: ds
              template:
                  templateRef: ApprovalShell
                  versionLabel: Version1
