pipeline:
    name: d
    identifier: d
    allowStageExecutions: false
    projectIdentifier: GS_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: d1
              identifier: d1
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: lightService
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: prod
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: temp
                              namespace: d1d1d11d
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: echo
                                identifier: echo
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo done
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
              tags: {}
