pipeline:
    name: de
    identifier: de
    projectIdentifier: GS_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: de
              identifier: de
              template:
                  templateRef: ApprovalShell
                  versionLabel: Version1
