pipeline:
    name: def
    identifier: def
    projectIdentifier: GS_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: appr1
              identifier: appr1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: Approval
                                identifier: approval
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.default_peeps
                                    approverInputs: []
              tags: {}
