pipeline:
    name: ip hd
    identifier: ip_hd
    projectIdentifier: GS_Manager
    orgIdentifier: default
    storeType: ""
    tags: {}
    stages:
        - stage:
              name: p1
              identifier: p1
              description: <+input>
              template:
                  templateRef: ApprovalShell
                  versionLabel: Version1
        - stage:
              name: a1
              identifier: a1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: ds
                                identifier: ds
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups: <+input>
                                    approverInputs: []
              tags: {}
