pipeline:
    name: kugytg
    identifier: kugytg
    projectIdentifier: GS_Manager
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: hlikuyhtgf
              identifier: hlikuyhtgf
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: kjhgf
                                identifier: kjhgf
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.adminsOnly
                                    approverInputs: []
              tags: {}
