pipeline:
    stages:
        - stage:
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: lightService
                      serviceDefinition:
                          type: Kubernetes
                          spec: {}
                  infrastructure:
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              releaseName: release-<+INFRA_KEY>
                              namespace: sdsdsdsdsd
                              connectorRef: temp
                      environmentRef: prod
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                      rollbackSteps:
                          - step:
                                type: K8sRollingRollback
                                timeout: 10m
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                spec: {}
              name: s1
              identifier: s1
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
    projectIdentifier: GS_Manager
    orgIdentifier: default
    name: rolling
    identifier: rolling
    description: test harness desc
    allowStageExecutions: false
