pipeline:
    name: expressions
    identifier: expressions
    projectIdentifier: Git_Sync_Delegate
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: s1
              identifier: s1
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: s1
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              artifacts:
                                  primary:
                                      type: DockerRegistry
                                      spec:
                                          connectorRef: <+input>
                                          imagePath: library/nginx
                                          tag: <+input>
                  infrastructure:
                      environmentRef: "e1"
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: <+input>
                              namespace: d111
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: d1
                                identifier: d1
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: d11d1
                                    environmentVariables: []
                                    outputVariables:
                                        - name: s1
                                          type: String
                                          value: s1
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
