pipeline:
    name: to be invalid
    identifier: to_be_invalid
    projectIdentifier: Git_Sync_Delegate
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              description: "valid description"
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: Http
                                name: ss
                                identifier: ss
                                spec:
                                    url: <+input>
                                    method: GET
                                    headers: []
                                    outputVariables: []
                                timeout: 10s
                  serviceDependencies: []
              tags: {}
