pipeline:
  name: "rem1"
  identifier: "rem1"
  projectIdentifier: "Ramyasimplegit"
  orgIdentifier: "default"
  tags: {}
  stages:
  - stage:
      name: "a1"
      identifier: "a1"
      description: ""
      type: "Approval"
      spec:
        execution:
          steps:
          - step:
              name: "e1"
              identifier: "e1"
              type: "HarnessApproval"
              timeout: "<+input>"
              spec:
                approvalMessage: "Please review the following information\nand approve\
                  \ the pipeline progression"
                includePipelineExecutionHistory: true
                approvers:
                  minimumCount: 1
                  disallowPipelineExecutor: false
                  userGroups: "<+input>"
                approverInputs: []
      tags: {}
  description: ""
