pipeline:
    name: remote with shellscript
    identifier: remote_with_shellscript
    projectIdentifier: On_Save_Policy_Sets
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: app1
              identifier: app1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: echo
                                identifier: echo
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo done
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                  serviceDependencies: []
              tags: {}
