pipeline:
    name: jbkhjvgh
    identifier: jbkhjvgh
    allowStageExecutions: false
    projectIdentifier: gs
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: kbhjvg
              identifier: kbhjvg
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: erdxtfyghk
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: n_bvc
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.CItestK8sConnectorO7oFXEw1x4
                              namespace: ihougyftdrtfuy
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: ercoul
                                identifier: ercoul
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: exit 0
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
